version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: test_php_redis__webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: digitalocean.com/php
    container_name: test_php_redis__app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Redis Service
  redis:
    container_name: test_php_redis__redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
